#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=example_job
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=1000m 
#SBATCH --time=01:00
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=v100:1
#SBATCH --gpus=v100:1
module load cuda
nvcc my_sha256.cu

./a.out 1
./a.out 2
./a.out 4
./a.out 8
./a.out 16
./a.out 32
./a.out 64
./a.out 128
./a.out 256
./a.out 512
./a.out 1024

#squeue -u sunsusan